language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
script:
  - pytest --ignore venv --cov=wags --cov=tests --cov-fail-under=89 --cov-report=term-missing
  - codecov

jobs:
  include:
    - stage: Publish docs
      python: 3.8
      script:
        - poetry -v
        - mkdocs build --verbose --clean --strict
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: site
        on:
          branch: master